language: node_js
node_js:
  - "0.12"
  - iojs
before_script:
  - wget https://github.com/antirez/disque/archive/master.tar.gz -O disque-master.tar.gz
  - tar xf disque-master.tar.gz
  - pushd disque-master; sudo make install; popd
script: make
